#!/bin/sh
#touch "/home/bart/paparazzi-tools/esp-udp-link/$1_$2.txt"
if [ "$1" = wlan1 ]; then
	if [ "$2" = up ]; then
		#touch "/home/bart/paparazzi-tools/esp-udp-link/$1_$2_jeej.txt"
		variable=$(nmcli c status | grep Hotspot)
		if [ -z "$variable" ]; then
    			#echo "Geen hotspot gevonden"
			#touch "/home/bart/paparazzi-tools/esp-udp-link/$1_$2_nohotspot.txt"
			sleep 1
	                nmcli d disconnect iface wlan1
	                sleep 1
        	        nmcli c up id Hotspot iface wlan1
		#else
			#cat $variable > "/home/bart/paparazzi-tools/esp-udp-link/debug.txt"
    			#echo "Is al hotspot, helemaal oKE"
		fi
	fi
fi
